import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smahh Website and Ticket Applicaiton",
  description: "Generated by Masami",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <nav>
          <div className="max-w-6xl w-full">
            <MainNav />
          </div>
        </nav> */}
      <Sidebar />
      <main className="mx-5 mt-14 sm:ml-[290px] sm:mt-3">
        {children}
      </main>
      </body>
    </html>
  );
}
