import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav";
import Sidebar from "@/components/Sidebar";
import { Separator } from "@/components/ui/separator";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smahh Website and Ticket Applicaiton",
  description: "Generated by Masami",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="w-full py-2 pl-5 pr-3">
            <div className="w-full">
              <MainNav />
            </div>
          </nav>
          <Separator />
          <div>
            <Sidebar />
            <main className="mx-5 mt-14 sm:ml-[290px] sm:mt-3">
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
